[package]
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"
name = "poise"
version = "0.1.0"
description = "A Discord bot framework for serenity"
documentation = "https://kangalioo.github.io/poise/"
license = "MIT"
repository = "https://github.com/kangalioo/poise/"

[dependencies]
tokio = { version = "1.4.0", default-features = false } # for async in general
futures = { version = "0.3.13", default-features = false } # for async in general
chrono = { version = "0.4.19", default-features = false } # interoperate with serenity timestamps
once_cell = { version = "1.7.2", default-features = false } # to store and set user data
poise_macros = { path = "macros" }
async-trait = { version = "0.1.48", default-features = false } # PopArgumentAsync trait
regex = { version = "1.5.4", default-features = false, features = ["std"] } # prefix

[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "gateway", "model", "utils", "rustls_backend", "unstable_discord_api", "voice"]

# version = "0.10.5"

git = "https://github.com/serenity-rs/serenity"
branch = "next"

# git = "https://github.com/kangalioo/serenity"
# branch = "poise-tailored"

# path = "../_downloaded/serenity"

[dependencies.songbird]
git = "https://github.com/Shirataki2/songbird.git"


[dev-dependencies]
# For the examples
tokio = { version = "1.4.0", features = ["rt-multi-thread"] }

[features]
default = ["collector"]

collector = ["serenity/collector"]
__internal_simdjson = ["serenity/simdjson"] # only used in CI
